"""initial schema

Baseline reproducing the schema previously created implicitly by
SQLModel.metadata.create_all() at app startup.

ADOPTING THIS ON AN EXISTING DATABASE:
    The tables already exist, so `alembic upgrade head` will fail with
    "relation \"jobs\" already exists". Adopt the baseline without re-running
    the DDL:

        alembic stamp head

    Only a *fresh* database should run `alembic upgrade head` for this
    revision. Every subsequent revision upgrades normally.

Revision ID: 52aec99ba09a
Revises:
Create Date: 2026-09-17 20:55:39.030664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                    # SQLModel AutoString, referenced by autogenerate
import pgvector.sqlalchemy         # pgvector VECTOR, referenced by autogenerate


# revision identifiers, used by Alembic.
revision: str = '52aec99ba09a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # infra/postgres/init.sql only runs on a *fresh* volume, so an existing
    # database may not have these. Both VECTOR columns below and the P3 trigram
    # indexes depend on them, so make the migration self-sufficient.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('apply_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('seniority_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('terms', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scrape_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'source', name='uq_jobs_external_id_source')
    )
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('content_raw', sa.Text(), nullable=True),
    sa.Column('content_clean', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crawl_depth', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_source_domain'), 'news_articles', ['source_domain'], unique=False)
    op.create_index(op.f('ix_news_articles_url'), 'news_articles', ['url'], unique=True)
    op.create_index(op.f('ix_news_articles_url_sha256'), 'news_articles', ['url_sha256'], unique=False)
    op.create_table('url_seen',
    sa.Column('url_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('canonical_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('url_sha256')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('url_seen')
    op.drop_index(op.f('ix_news_articles_url_sha256'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_url'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_source_domain'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
