"""timestamptz + google oauth user fields

Revision ID: c3f4373519e4
Revises: a0149e01d709
Create Date: 2026-10-01 02:30:38.325294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                    # SQLModel emits sqlmodel.sql.sqltypes.AutoString
import pgvector.sqlalchemy         # pgvector emits pgvector.sqlalchemy.vector.VECTOR
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3f4373519e4'
down_revision: Union[str, Sequence[str], None] = 'a0149e01d709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Two hand-edits over the autogenerated output, both load-bearing:

    1. Each TIMESTAMP -> TIMESTAMPTZ conversion carries an explicit
       `USING <col> AT TIME ZONE 'UTC'`. Stored values are naive UTC; the
       default cast reinterprets them in the SESSION timezone, which shifts
       every timestamp by the local offset (verified: 12:00 -> 16:00 under
       America/New_York).
    2. users.is_active gets a server_default so the NOT NULL add succeeds on
       a table that already has rows.
    """
    op.alter_column('jobs', 'posted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True,
               postgresql_using="posted_at AT TIME ZONE 'UTC'")
    op.alter_column('jobs', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=False,
               postgresql_using="scraped_at AT TIME ZONE 'UTC'")
    op.alter_column('jobs', 'enriched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True,
               postgresql_using="enriched_at AT TIME ZONE 'UTC'")
    op.alter_column('jobs', 'description_fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True,
               postgresql_using="description_fetched_at AT TIME ZONE 'UTC'")
    op.alter_column('news_articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True,
               postgresql_using="published_at AT TIME ZONE 'UTC'")
    op.alter_column('news_articles', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=False,
               postgresql_using="scraped_at AT TIME ZONE 'UTC'")
    op.alter_column('news_articles', 'enriched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True,
               postgresql_using="enriched_at AT TIME ZONE 'UTC'")
    op.alter_column('url_seen', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=False,
               postgresql_using="first_seen_at AT TIME ZONE 'UTC'")
    op.add_column('users', sa.Column('google_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # server_default is required: adding a NOT NULL column to a table that
    # already has rows fails outright without one. Existing accounts are
    # active by definition.
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False,
                                     server_default=sa.text('true')))
    op.add_column('users', sa.Column('last_login_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'google_sub')
    op.alter_column('url_seen', 'first_seen_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('news_articles', 'enriched_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('news_articles', 'scraped_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('news_articles', 'published_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('jobs', 'description_fetched_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('jobs', 'enriched_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('jobs', 'scraped_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('jobs', 'posted_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
